// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Vendeghaz;
//
//    var guests = Guests.FromJson(jsonString);

namespace Vendeghaz
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Guests
    {
        [JsonProperty("g_id")]
        public long GId { get; set; }

        [JsonProperty("g_name")]
        public string GName { get; set; }

        [JsonProperty("g_species")]
        public string GSpecies { get; set; }

        [JsonProperty("g_gender")]
        public string GGender { get; set; }

        [JsonProperty("g_birthdate")]
        public DateTimeOffset GBirthdate { get; set; }

        [JsonProperty("g_in_date")]
        public DateTimeOffset GInDate { get; set; }

        [JsonProperty("g_in_place")]
        public string GInPlace { get; set; }

        [JsonProperty("g_other")]
        public string GOther { get; set; }

        [JsonProperty("g_image")]
        public GImage GImage { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset? UpdatedAt { get; set; }

        [JsonProperty("deleted_at")]
        public DateTimeOffset? DeletedAt { get; set; }
    }

    public partial class GImage
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("data")]
        public long[] Data { get; set; }
    }

    public partial class Guests
    {
        public static Guests[] FromJson(string json) => JsonConvert.DeserializeObject<Guests[]>(json, Vendeghaz.GuestsConverter.Settings);
    }

    public static class GuestsSerialize
    {
        public static string ToJson(this Guests[] self) => JsonConvert.SerializeObject(self, Vendeghaz.GuestsConverter.Settings);
    }

    internal static class GuestsConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
